-- ============================================
-- 013 — Re-number cards by rarity blocks
-- Rainbow 000-005, Diamond 006-017, Gold 018-035,
-- Rare 036-059, Common 060-119
-- ============================================

TRUNCATE pack_user_cards CASCADE;
DELETE FROM pack_generated_packs;
DELETE FROM pack_cards;

UPDATE pack_generation_config SET generated = false, generated_at = NULL WHERE id = 1;

INSERT INTO pack_cards (number, name, description, rarity, pack_type) VALUES
  -- ═══ RAINBOW 000-005 (2 per pool) ═══
  (0,  'Rainbow #000', 'Carta arcobaleno leggendaria', 'rainbow', 'red'),
  (1,  'Rainbow #001', 'Carta arcobaleno leggendaria', 'rainbow', 'red'),
  (2,  'Rainbow #002', 'Carta arcobaleno leggendaria', 'rainbow', 'green'),
  (3,  'Rainbow #003', 'Carta arcobaleno leggendaria', 'rainbow', 'green'),
  (4,  'Rainbow #004', 'Carta arcobaleno leggendaria', 'rainbow', 'blue'),
  (5,  'Rainbow #005', 'Carta arcobaleno leggendaria', 'rainbow', 'blue'),

  -- ═══ DIAMOND 006-017 (4 per pool) ═══
  (6,  'Diamond #006', 'Carta diamante rara', 'diamond', 'red'),
  (7,  'Diamond #007', 'Carta diamante rara', 'diamond', 'red'),
  (8,  'Diamond #008', 'Carta diamante rara', 'diamond', 'red'),
  (9,  'Diamond #009', 'Carta diamante rara', 'diamond', 'red'),
  (10, 'Diamond #010', 'Carta diamante rara', 'diamond', 'green'),
  (11, 'Diamond #011', 'Carta diamante rara', 'diamond', 'green'),
  (12, 'Diamond #012', 'Carta diamante rara', 'diamond', 'green'),
  (13, 'Diamond #013', 'Carta diamante rara', 'diamond', 'green'),
  (14, 'Diamond #014', 'Carta diamante rara', 'diamond', 'blue'),
  (15, 'Diamond #015', 'Carta diamante rara', 'diamond', 'blue'),
  (16, 'Diamond #016', 'Carta diamante rara', 'diamond', 'blue'),
  (17, 'Diamond #017', 'Carta diamante rara', 'diamond', 'blue'),

  -- ═══ GOLD 018-035 (6 per pool) ═══
  (18, 'Gold #018', 'Carta dorata speciale', 'gold', 'red'),
  (19, 'Gold #019', 'Carta dorata speciale', 'gold', 'red'),
  (20, 'Gold #020', 'Carta dorata speciale', 'gold', 'red'),
  (21, 'Gold #021', 'Carta dorata speciale', 'gold', 'red'),
  (22, 'Gold #022', 'Carta dorata speciale', 'gold', 'red'),
  (23, 'Gold #023', 'Carta dorata speciale', 'gold', 'red'),
  (24, 'Gold #024', 'Carta dorata speciale', 'gold', 'green'),
  (25, 'Gold #025', 'Carta dorata speciale', 'gold', 'green'),
  (26, 'Gold #026', 'Carta dorata speciale', 'gold', 'green'),
  (27, 'Gold #027', 'Carta dorata speciale', 'gold', 'green'),
  (28, 'Gold #028', 'Carta dorata speciale', 'gold', 'green'),
  (29, 'Gold #029', 'Carta dorata speciale', 'gold', 'green'),
  (30, 'Gold #030', 'Carta dorata speciale', 'gold', 'blue'),
  (31, 'Gold #031', 'Carta dorata speciale', 'gold', 'blue'),
  (32, 'Gold #032', 'Carta dorata speciale', 'gold', 'blue'),
  (33, 'Gold #033', 'Carta dorata speciale', 'gold', 'blue'),
  (34, 'Gold #034', 'Carta dorata speciale', 'gold', 'blue'),
  (35, 'Gold #035', 'Carta dorata speciale', 'gold', 'blue'),

  -- ═══ RARE 036-059 (8 per pool) ═══
  (36, 'Rare #036', 'Carta rara', 'rare', 'red'),
  (37, 'Rare #037', 'Carta rara', 'rare', 'red'),
  (38, 'Rare #038', 'Carta rara', 'rare', 'red'),
  (39, 'Rare #039', 'Carta rara', 'rare', 'red'),
  (40, 'Rare #040', 'Carta rara', 'rare', 'red'),
  (41, 'Rare #041', 'Carta rara', 'rare', 'red'),
  (42, 'Rare #042', 'Carta rara', 'rare', 'red'),
  (43, 'Rare #043', 'Carta rara', 'rare', 'red'),
  (44, 'Rare #044', 'Carta rara', 'rare', 'green'),
  (45, 'Rare #045', 'Carta rara', 'rare', 'green'),
  (46, 'Rare #046', 'Carta rara', 'rare', 'green'),
  (47, 'Rare #047', 'Carta rara', 'rare', 'green'),
  (48, 'Rare #048', 'Carta rara', 'rare', 'green'),
  (49, 'Rare #049', 'Carta rara', 'rare', 'green'),
  (50, 'Rare #050', 'Carta rara', 'rare', 'green'),
  (51, 'Rare #051', 'Carta rara', 'rare', 'green'),
  (52, 'Rare #052', 'Carta rara', 'rare', 'blue'),
  (53, 'Rare #053', 'Carta rara', 'rare', 'blue'),
  (54, 'Rare #054', 'Carta rara', 'rare', 'blue'),
  (55, 'Rare #055', 'Carta rara', 'rare', 'blue'),
  (56, 'Rare #056', 'Carta rara', 'rare', 'blue'),
  (57, 'Rare #057', 'Carta rara', 'rare', 'blue'),
  (58, 'Rare #058', 'Carta rara', 'rare', 'blue'),
  (59, 'Rare #059', 'Carta rara', 'rare', 'blue'),

  -- ═══ COMMON 060-119 (20 per pool) ═══
  (60, 'Common #060', 'Carta comune', 'common', 'red'),
  (61, 'Common #061', 'Carta comune', 'common', 'red'),
  (62, 'Common #062', 'Carta comune', 'common', 'red'),
  (63, 'Common #063', 'Carta comune', 'common', 'red'),
  (64, 'Common #064', 'Carta comune', 'common', 'red'),
  (65, 'Common #065', 'Carta comune', 'common', 'red'),
  (66, 'Common #066', 'Carta comune', 'common', 'red'),
  (67, 'Common #067', 'Carta comune', 'common', 'red'),
  (68, 'Common #068', 'Carta comune', 'common', 'red'),
  (69, 'Common #069', 'Carta comune', 'common', 'red'),
  (70, 'Common #070', 'Carta comune', 'common', 'red'),
  (71, 'Common #071', 'Carta comune', 'common', 'red'),
  (72, 'Common #072', 'Carta comune', 'common', 'red'),
  (73, 'Common #073', 'Carta comune', 'common', 'red'),
  (74, 'Common #074', 'Carta comune', 'common', 'red'),
  (75, 'Common #075', 'Carta comune', 'common', 'red'),
  (76, 'Common #076', 'Carta comune', 'common', 'red'),
  (77, 'Common #077', 'Carta comune', 'common', 'red'),
  (78, 'Common #078', 'Carta comune', 'common', 'red'),
  (79, 'Common #079', 'Carta comune', 'common', 'red'),
  (80, 'Common #080', 'Carta comune', 'common', 'green'),
  (81, 'Common #081', 'Carta comune', 'common', 'green'),
  (82, 'Common #082', 'Carta comune', 'common', 'green'),
  (83, 'Common #083', 'Carta comune', 'common', 'green'),
  (84, 'Common #084', 'Carta comune', 'common', 'green'),
  (85, 'Common #085', 'Carta comune', 'common', 'green'),
  (86, 'Common #086', 'Carta comune', 'common', 'green'),
  (87, 'Common #087', 'Carta comune', 'common', 'green'),
  (88, 'Common #088', 'Carta comune', 'common', 'green'),
  (89, 'Common #089', 'Carta comune', 'common', 'green'),
  (90, 'Common #090', 'Carta comune', 'common', 'green'),
  (91, 'Common #091', 'Carta comune', 'common', 'green'),
  (92, 'Common #092', 'Carta comune', 'common', 'green'),
  (93, 'Common #093', 'Carta comune', 'common', 'green'),
  (94, 'Common #094', 'Carta comune', 'common', 'green'),
  (95, 'Common #095', 'Carta comune', 'common', 'green'),
  (96, 'Common #096', 'Carta comune', 'common', 'green'),
  (97, 'Common #097', 'Carta comune', 'common', 'green'),
  (98, 'Common #098', 'Carta comune', 'common', 'green'),
  (99, 'Common #099', 'Carta comune', 'common', 'green'),
  (100, 'Common #100', 'Carta comune', 'common', 'blue'),
  (101, 'Common #101', 'Carta comune', 'common', 'blue'),
  (102, 'Common #102', 'Carta comune', 'common', 'blue'),
  (103, 'Common #103', 'Carta comune', 'common', 'blue'),
  (104, 'Common #104', 'Carta comune', 'common', 'blue'),
  (105, 'Common #105', 'Carta comune', 'common', 'blue'),
  (106, 'Common #106', 'Carta comune', 'common', 'blue'),
  (107, 'Common #107', 'Carta comune', 'common', 'blue'),
  (108, 'Common #108', 'Carta comune', 'common', 'blue'),
  (109, 'Common #109', 'Carta comune', 'common', 'blue'),
  (110, 'Common #110', 'Carta comune', 'common', 'blue'),
  (111, 'Common #111', 'Carta comune', 'common', 'blue'),
  (112, 'Common #112', 'Carta comune', 'common', 'blue'),
  (113, 'Common #113', 'Carta comune', 'common', 'blue'),
  (114, 'Common #114', 'Carta comune', 'common', 'blue'),
  (115, 'Common #115', 'Carta comune', 'common', 'blue'),
  (116, 'Common #116', 'Carta comune', 'common', 'blue'),
  (117, 'Common #117', 'Carta comune', 'common', 'blue'),
  (118, 'Common #118', 'Carta comune', 'common', 'blue'),
  (119, 'Common #119', 'Carta comune', 'common', 'blue');
